config/routes.rb
Rails.application.routes.draw do

  root 'houses#index'
  resources :houses, only: [:index, :show, :new, :create] do
    resources :members, only: [:new, :create]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/house.rb
class House < ApplicationRecord
  has_many :members

  validates :name, presence: true
  validates :author, presence: true
  validates :source, presence: true
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :house

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :house, presence: true

  def name
    [first_name, last_name].join(' ')
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  
  protect_from_forgery unless: -> { request.format.json? }
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController

  def index
    @houses = House.all
  end

  def show
    @house = House.find(params[:id])
    @members = @house.members
  end

  def new
    @house = House.new
  end

  def create
    @house = House.new(house_params)
    if @house.save
      redirect_to @house, notice: "House added successfully"
    else
      flash[:notice] = "Failed to save House."
      render :new
    end
  end


  private

  def house_params
    params.require(:house).permit(:name, :author, :source, :motto)
  end

end

app/controllers/members_controller.rb
class MembersController < ApplicationController

  def new
    @house = House.find(params[:house_id])
    @member = Member.new
    @member.house = @house
    @members = @house.members
  end

  def create
    @house = House.find(params[:house_id])
    @member = Member.new(member_params)
    @member.house = @house
    @members = @house.members

    if @member.save
      flash[:notice] = "Member added successfully"
      redirect_to house_path(@house)
    else
      flash[:notice] = "Failed to save Member"
      render :new
    end
  end

  private

  def member_params
    params.require(:member).permit(:first_name, :last_name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/houses/_form.html.erb
<%= form_for(@house) do |f| %>

  <% if house.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(house.errors.count, "error") %> prohibited this house from being saved:</h2>

      <ul>
      <% house.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>

  <div class="field">
    <%= f.label :source %><br />
    <%= f.text_field :source %>
  </div>

  <div class="field">
    <%= f.label :motto %><br />
    <%= f.text_field :motto %>
  </div>

  <div class="actions">
    <%= f.submit "Add House"%>
  </div>
<% end %>

app/views/houses/index.html.erb
<h3>Current Houses:</h3>

<ul>
<% @houses.each do |house| %>
  <li> <%= link_to house.name, house_path(house) %> </li>
<% end %>
</ul>

<%= link_to 'Add New House', new_house_path %>

app/views/houses/new.html.erb
<h1>New House Form</h1>

<%= render 'form', house: @house %>
<%= link_to 'Home', houses_path %>

app/views/houses/show.html.erb
<h3>  House Name: <%= @house.name %>  </h3>
<h3>  Author: <%= @house.author %>  </h3>
<h3>  Source: <%= @house.source %>  </h3>

<% if @house.motto != "" %>
  <h3>  House Motto: <%= @house.motto %>  </h3>
<% end %>

<% if @house.members != [] %>
  <h3>Members:</h3>
<% end %>

<ul>
  <% @members.each do |member| %>
    <li>
      <%= member.name %><br>
      <%= "Created at: #{member.created_at.strftime("%B %d %Y")}" %>
    </li>
<% end %>
</ul>

<%= link_to 'Add a House Member', new_house_member_path(@house) %><br>
<%= link_to 'Home', houses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fantasy Houses</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |key, value| %>
  <%= value %>
<% end %>
<%= yield %>

</body>
</html>

app/views/members/new.html.erb
<h3><%= "New House #{@house.name} Member Form" %></h3>

<%= form_for [@house, @member] do |f| %>

  <% if @member.errors.any? %>
    <div id="error_explanation">
      <h4><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h4>

      <ul>
      <% @member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name, "First Name"%><br />
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name, "Last Name" %><br />
    <%= f.text_field :last_name %>
  </div>

  <div class="actions">
    <%= f.submit "Add Member"%>
  </div>
<% end %>